server:
  host: "0.0.0.0"
  port: "8080"
  timeout: 60s
  userToken: "user"
  adminToken: "admin"

postgres:
  host: "0.0.0.0"
  port: "5432"
  user: "postgres"
  password: "postgres"
  dbname: "test"
  sslMode: "disable"